#!/usr/bin/env python3
"""
D-Bus handler for fcitx5-lotus configuration.
Communicates with fcitx5 via D-Bus to read/write configuration.
"""

import os
from typing import Dict, Any, Optional
from pathlib import Path


class LotusDBusHandler:
    """
    Handler for D-Bus communication with fcitx5-lotus.
    Reads configuration from fcitx5 config files.
    """

    def __init__(self):
        self.config_dir = self._get_config_dir()
        self.config_file = os.path.join(self.config_dir, "lotus.conf")
        self._config_cache: Dict[str, Any] = {}
        self._load_config()

    def _get_config_dir(self) -> str:
        """Get the fcitx5 config directory."""
        xdg_config = os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
        return os.path.join(xdg_config, "fcitx5", "conf")

    def _load_config(self):
        """Load configuration from file."""
        if not os.path.exists(self.config_file):
            # Try default config location
            default_config = "/usr/share/fcitx5/addon/lotus/lotus.conf"
            if os.path.exists(default_config):
                self._parse_config_file(default_config)
            return

        self._parse_config_file(self.config_file)

    def _parse_config_file(self, filepath: str):
        """Parse fcitx5 configuration file."""
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                current_section = None

                for line in f:
                    line = line.strip()

                    # Skip empty lines and comments
                    if not line or line.startswith("#"):
                        continue

                    # Section header
                    if line.startswith("[") and line.endswith("]"):
                        current_section = line[1:-1]
                        continue

                    # Key-Value pair
                    if "=" in line:
                        key, value = line.split("=", 1)
                        key = key.strip()
                        value = value.strip()

                        # Store with section prefix
                        if current_section:
                            full_key = f"{current_section}/{key}"
                        else:
                            full_key = key

                        self._config_cache[full_key] = self._parse_value(value)

                        # Also store simple key
                        self._config_cache[key] = self._parse_value(value)

        except Exception as e:
            print(f"Error loading config: {e}")

    def _parse_value(self, value: str) -> Any:
        """Parse configuration value."""
        # Boolean
        if value.lower() in ("true", "yes", "1"):
            return True
        if value.lower() in ("false", "no", "0"):
            return False

        # Try integer
        try:
            return int(value)
        except ValueError:
            pass

        # Try float
        try:
            return float(value)
        except ValueError:
            pass

        # String (remove quotes if present)
        value = value.strip()
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]

        return value

    def get_config(self) -> Dict[str, Any]:
        """Get all configuration as dictionary."""
        return self._config_cache.copy()

    def get_value(self, key: str, default: Any = None) -> Any:
        """Get a specific configuration value."""
        return self._config_cache.get(key, default)

    def set_value(self, key: str, value: Any):
        """Set a configuration value."""
        self._config_cache[key] = value
        self._save_config()

    def _save_config(self):
        """Save configuration to file."""
        try:
            # Ensure directory exists
            os.makedirs(self.config_dir, exist_ok=True)

            with open(self.config_file, "w", encoding="utf-8") as f:
                f.write("# Fcitx5-Lotus Configuration\n")
                f.write("# Auto-generated by Lotus Settings GUI\n\n")

                # Group values by section
                sections: Dict[str, Dict[str, Any]] = {}

                for key, value in self._config_cache.items():
                    if "/" in key:
                        section, name = key.split("/", 1)
                        if section not in sections:
                            sections[section] = {}
                        sections[section][name] = value
                    else:
                        if "General" not in sections:
                            sections["General"] = {}
                        sections["General"][key] = value

                # Write sections
                for section_name, section_data in sections.items():
                    f.write(f"[{section_name}]\n")
                    for key, value in section_data.items():
                        # Format value
                        if isinstance(value, bool):
                            str_value = "True" if value else "False"
                        elif isinstance(value, str):
                            str_value = f'"{value}"'
                        else:
                            str_value = str(value)
                        f.write(f"{key}={str_value}\n")
                    f.write("\n")

        except Exception as e:
            print(f"Error saving config: {e}")


class LotusDBusInterface:
    """
    Alternative D-Bus interface for real-time communication with fcitx5.
    This uses pydbus or similar to communicate with fcitx5's D-Bus interface.
    """

    def __init__(self):
        self.bus_name = "org.freedesktop.fcitx5.Lotus"
        self.object_path = "/org/freedesktop/fcitx5/lotus"
        self.interface_name = "org.freedesktop.fcitx5.Lotus"

        self._dbus = None
        self._proxy = None
        self._init_dbus()

    def _init_dbus(self):
        """Initialize D-Bus connection."""
        try:
            from pydbus import SessionBus

            self._dbus = SessionBus()

            # Try to get the lotus object
            try:
                self._proxy = self._dbus.get(self.bus_name, self.object_path)
            except Exception:
                # Lotus might not be running, use fallback
                self._proxy = None
        except ImportError:
            # pydbus not available
            self._dbus = None
            self._proxy = None
        except Exception as e:
            print(f"D-Bus initialization error: {e}")
            self._dbus = None
            self._proxy = None

    def is_available(self) -> bool:
        """Check if D-Bus interface is available."""
        return self._proxy is not None

    def get_config_value(self, key: str) -> Optional[Any]:
        """Get configuration value via D-Bus."""
        if not self._proxy:
            return None

        try:
            return self._proxy.GetValue(key)
        except Exception:
            return None

    def set_config_value(self, key: str, value: Any) -> bool:
        """Set configuration value via D-Bus."""
        if not self._proxy:
            return False

        try:
            self._proxy.SetValue(key, value)
            return True
        except Exception as e:
            print(f"Error setting config via D-Bus: {e}")
            return False

    def reset_config(self):
        """Reset configuration to defaults via D-Bus."""
        if not self._proxy:
            return

        try:
            self._proxy.Reset()
        except Exception as e:
            print(f"Error resetting config: {e}")


# Default handler instance
default_handler = LotusDBusHandler()


def get_config() -> Dict[str, Any]:
    """Get configuration dictionary."""
    return default_handler.get_config()


def get_value(key: str, default: Any = None) -> Any:
    """Get a specific configuration value."""
    return default_handler.get_value(key, default)


def set_value(key: str, value: Any):
    """Set a configuration value."""
    default_handler.set_value(key, value)
